name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Trigger deploy via Render API
        id: trigger_deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          SERVICE_ID="srv-d34gj33ipnbc73fv5sh0"
          echo "🚀 Triggering deploy on Render service $SERVICE_ID..."
          
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY")
          
          echo "response_code=$response" >> $GITHUB_OUTPUT
          
          if [ "$response" -eq 200 ] || [ "$response" -eq 201 ] || [ "$response" -eq 202 ]; then
            echo "✅ Deploy triggered successfully."
          else
            echo "❌ Failed to trigger deploy. HTTP status code: $response"
            exit 1
          fi
